version: '2'

services:
  jupyter:
    image: "bonnevm/machine-learning-base"
    ports:
      - "8888:8888"
    volumes:
      - ..:/mydata  # mapping source code root
      - ../notebooks:/home/icebaby/notebooks # mapping notebooks root
      - ../build/nltk_data:/home/icebaby/nltk_data # mapping nltk_data root (not in git)
