version: '2'

services:
  jupyter:
    image: "bonnevm/machine-learning-base"
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/home/icebaby/notebooks
      - ../notebooks/nltk_data:/home/icebaby/nltk_data
      - ..:/mydata
